### ISSUE TITLE
Imagery Basemaps Not Working in QRAVE (0.8.0)

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#646]
I was working in [this VBET project](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/49936480-af64-4f7a-96aa-fdbfa7e1e393) today using RAVE 0.8.0 and wasn't able to bring in any imagery basemaps through the RAVE Toolbar. This is the error message:

```
2022-12-01T09:12:33     INFO    Fetching WMS Capabilities: https://services.nationalmap.gov/arcgis/services/USGSNAIPImagery/ImageServer/WMSServer
2022-12-01T09:12:33     CRITICAL    Exception: Opening and ending tag mismatch: br line 9 and p, line 10, column 5 (, line 10)
2022-12-01T09:14:26     INFO    Fetching WMS Capabilities: https://services.terrascope.be/wms/v2
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 58, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 62, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 78, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 94, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 110, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 126, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 142, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 158, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 174, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 190, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 206, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 222, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 238, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 254, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 270, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 286, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 302, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 318, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 334, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 350, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 366, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 382, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 398, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 414, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 430, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 446, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 462, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 478, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 494, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 510, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 526, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 542, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 558, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 574, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 590, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 606, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 622, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 638, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 654, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 670, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 686, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 702, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 718, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 734, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 750, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 766, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 782, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 798, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 814, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 830, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 846, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 862, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 878, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 894, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 910, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:31     WARNING    Error parsing basemap layer Exception: 'NoneType' object has no attribute 'text', Line: 926, Url: https://services.terrascope.be/wms/v2?service=wms&request=GetCapabilities&version=1.0.0
2022-12-01T09:14:35     INFO    Fetching WMS Capabilities: https://services.nationalmap.gov/arcgis/services/USGSNAIPPlus/MapServer/WmsServer
2022-12-01T09:14:36     CRITICAL    Exception: Opening and ending tag mismatch: br line 9 and p, line 10, column 5 (, line 10)
```
